---
- hosts: checkpoint
  become: false
  gather_facts: false
  vars_files:
    - vault_prod.yml
  tasks:
  - name: login to checkpoint MGT via the CheckPoint Module
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ mgmt_user }}"
        password: "{{ mgmt_password }}"
        management: "{{ mgmt_server }}"
      fingerprint: 56:2B:FF:3C:A1:B2:38:29:E6:C6:47:FE:AA:08:D9:D9:54:66:62:12
    register: login_response

  - name: add host 'api_created_host'
    check_point_mgmt:
      command: add-host
      parameters:
        name: api_created_host
        ip-address: 1.2.3.5
      session-data: "{{ login_response }}"

  - name: add group 'api_created_group'
    check_point_mgmt:
      command: add-group
      parameters:
        name: api_created_group
        members:
          - api_created_host
      session-data: "{{ login_response }}"

  - name: create new tcp service 'tcp_1005_script'
    check_point_mgmt:
      command: add-service-tcp
      parameters:
        name: tcp_1005_script
        port: '1005'
      session-data: '{{ login_response }}'

  - name: create a section called 'script_rules'
    check_point_mgmt:
      command: add-access-section
      parameters:
        layer: Network
        name: script_rules
        position: top
      session-data: '{{ login_response }}'

  - name: create rule at the top of a section called 'created by ansible playbook'
    check_point_mgmt:
      command: add-access-rule
      parameters:
        layer: network
        name: created by ansible playbook
        position:
          below: script_rules
        source:
          - any
        destination:
          - api_created_host
        service:
          - tcp_1005_script
        action: accept
        track:
          type: log
      session-data: '{{ login_response }}'

  - name: publish
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"

  - name: logout
    check_point_mgmt:
      command: logout
      session-data: '{{ login_response }}'
