---
  # configure file for websiteX
- name: Copy httpd.conf files
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart apache service

- name: Send index.html from template
  template: src=index.html.j2 dest:/var/www/html/index.html
  notify:
    - restart apache service
