---

- hosts: ubuntu*
  become: True
  gather_facts: True

  tasks:
    - name: Only run update cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

#    - name: Upgrade all packages to the latest version
#      apt:
#      name: "*"
#      state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Run the equivalent of apt-get update as a separate step
      apt:
        update_cache: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
