---
- hosts: ubuntu
  become: true
  gather_facts: true

  tasks:
    - name: Only run update cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"
