---
- hosts: linux
  become: true
  gather_facts: true

  tasks:
    - name: Only run update cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Safe upgrade all packages to the latest version if OS is Debian based
      apt:
        upgrade: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Clean system with autoremove
      apt:
        autoremove: yes
